# Change these first
owner: AlexandreBrg # Your GitHub organization or username, where this repository lives
repo: services-uptime # The name of this repository

sites:
  - name: Polyflix
    url: https://polyflix.dopolytech.fr
  - name: Polyflix MinIO
    url: https://console.minio.polyflix.dopolytech.fr/
  - name: Polyflix SSO
    url: https://sso.polyflix.dopolytech.fr/
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /services-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Polyflix Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Polyflix is a knowledge platform where you are able to learn through watching conference videos. 
  navbar:
    - title: Polyflix
      href: https://polyflix.dopolytech.fr
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
